### ISSUE TITLE
Schedule column data-id 가 동일하게 생성되는 경우 발생

### ISSUE THREAD

**Issue by bangdler** [nanjeong/todo-list#11]
- 문제
  - 새로고침을 하다보면 동일한 시간 id 로 column 이 생성되면서 한 column 에 모든 card 가 추가되는 상황이 발생함.
![image](https://user-images.githubusercontent.com/90082464/162216863-c2058d09-2d9b-4ec3-9124-18d4440b473b.png)

**Comment by nanjeong** [comment]
ScheduleColumn에서 id를 Date말고 다른 걸로 해줘야겠네요...😓
